name: Build and Deploy Website

on:
  push:
    branches:
      - main
    # Abaikan perubahan yang berasal dari sitemap agar tidak terjadi perulangan tak terbatas
    paths-ignore:
      - 'sitemap.xml'
      - 'robots.txt'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode Repositori
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Jalankan Skrip Pembuat Sitemap
        run: node main.js

      - name: Commit Hasil Sitemap (Dengan Force agar tidak konflik)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update sitemap.xml dan robots.txt"
          file_pattern: sitemap.xml robots.txt
          push_options: '--force'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact Website
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
