name: Clear Workflow Runs
on:
  workflow_dispatch: # Agar bisa dijalankan secara manual lewat tab Actions

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # Hapus semua tanpa sisa hari
          keep_minimum_runs: 0
          # Opsional: Jika masih error pada run tertentu, 
          # Anda bisa abaikan atau targetkan workflow tertentu saja
