name: Generate Sitemap

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'sitemap.xml'
      - 'robots.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Jalankan Skrip Sitemap
        run: node main.js

      - name: Simpan Sitemap ke Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update sitemap.xml dan robots.txt"
          file_pattern: sitemap.xml robots.txt
          push_options: '--force'
